version: 2.1

commands:
  destroy-environment:
    description: Destroy APP cloudformation stacks given a workflow ID.
    parameters:
      # Add parameter here   
    steps:
      - run:
          name: Delete S3 content
          when: on_fail
          command: |
            aws s3 rm s3://awscicd-${CIRCLE_WORKFLOW_ID:0:7} --recursive
            exit 0
      - run:
          name: Destroy environments
          when: on_fail
          command: |
            aws cloudformation --region eu-central-1 delete-stack --stack-name awscicd-${CIRCLE_WORKFLOW_ID:0:7}
            exit 0

jobs:
  build-app:
    docker:
      - image: circleci/node:16.13.0
    steps:
      - checkout
      - run:
          name: Build front-end
          command: |
            # Your code here
            sudo npm i
            npm run build
      - save_cache:
          key: frontend-build
          paths: [node_modules]
  lint-app:
    docker:
      - image: circleci/node:16.13.0
    steps:
      # Checkout code from git
      - checkout
      # Restore from cache
      - restore_cache:
          key: frontend-build
      # Your job code here
      - run:
          name: test frontend
          command: |
            # Your code here
            npm run lint
  test-app:
    docker:
      - image: circleci/node:16.13.0
    steps:
      # Checkout code from git
      - checkout
      # Restore from cache
      - restore_cache:
          key: frontend-build
      # Your job code here
      - run:
          name: test frontend
          command: |
            # Your code here
            npm run test:coverage

  deploy-infrastructure:
    docker:
      # Docker image here that supports AWS CLI
      - image: amazon/aws-cli
    steps:
      # Checkout code from git
      - checkout
      - run:
          name: Install Tar since its a requesite 
          command: |
            yum -y install tar gzip jq git
      - run:
          name: Ensure front-end infrastructure exist
          command: |
            aws cloudformation deploy \
              --region eu-central-1 \
              --template-file .circleci/files/app.yml \
              --stack-name "awscicd-${CIRCLE_WORKFLOW_ID:0:7}"\
              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}" \
              --tags Name=awscicd-${CIRCLE_WORKFLOW_ID:0:7} 
#       # Here's where you will add some code to rollback on failure     
      - destroy-environment 

workflows:
  default:
    jobs:
      - build-app
      - lint-app:
          requires: [build-app]
      - test-app:
          requires: [build-app]
      - deploy-infrastructure:
          requires: [test-app, lint-app]
          filters:
            branches:
              #only: [test-feature-branch]
              only: [main]